config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'articles/index'
  resources :articles do
    resources :comments
    resources :comms
  end
  resources :comments do
    resources :comms
  end
  resources :comms

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :comms, through: :comments
end

app/models/comm.rb
class Comm < ActiveRecord::Base
  belongs_to :comment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  has_many :comms, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, through: :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create

    @article = Article.new(article_params)

    @article.users_id = current_user.id
    @article.title = current_user.email

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.users_id == current_user.id
      if @article.update(article_params)
        redirect_to @article, notice: 'Item was changed'
      else
        render 'edit'
      end
    else
      redirect_to articles_path, notice: 'You can`t edit or delete this'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.users_id == current_user.id
      @article.destroy
      redirect_to articles_path, notice: 'Item was removed'
    else
      redirect_to articles_path, notice: 'You can`t edit or delete this'
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.users_id = current_user.id
    @comment.commenter = current_user.email
    if @comment.save
      redirect_to article_path(@article)
    else
      article_path(@article)
    end

  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.users_id == current_user.id
      if @comment.update(comment_params)
        redirect_to comment_path(@comment), notice: 'Item was changed'
      else
        render 'edit'
      end
    else
      redirect_to comment_path(@comment), notice: 'You can`t edit or delete this'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.users_id == current_user.id
      @comment.destroy
      redirect_to article_path(@article), notice: 'Item was removed'
    else
      redirect_to article_path(@article), notice: 'You can`t edit or delete this'
    end

  end

  def show
    @comment = Comment.find(params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :users_id)


  end


end

app/controllers/comms_controller.rb
class CommsController < ApplicationController

  def create
    @comment = Comment.find(params[:comment_id])
    @comm = @comment.comms.build(comm_params)
    @comm.users_id = current_user.id
    @comm.commenter = current_user.email
    if @comm.save
      redirect_to comment_path(@comment)
    else
      redirect_to comment_path(@comment)
    end
  end

  def update
    @comm = Comm.find(params[:id])
    if @comm.users_id == current_user.id
      if @comm.update(comm_params)
        redirect_to comm_path(@comm), notice: 'Item was changed'
      else
        render 'edit'
      end
    else
      redirect_to comm_path(@comm), notice: 'You can`t edit or delete this'
    end
  end

  def edit
    @comm = Comm.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @comm = @comment.comms.find(params[:id])
    if @comm.users_id == current_user.id
      @comm.destroy
      redirect_to comment_path(@comment), notice: 'Item was removed'
    else
      redirect_to comment_path(@comment), notice: 'You can`t edit or delete this'
    end
  end

  def show
    @comm = Comm.find(params[:id])
  end


  private
  def comm_params
    params.require(:comm).permit(:commenter, :body)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/comms_helper.rb
module CommsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <p>
      <%= f.text_area :text, size: "58x6" %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<div align="center">
  <h1>Change article</h1>

  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div align="center"><h1>Listing Articles</h1>
  <div class="c"><%= link_to 'New article', new_article_path %></div>
  <table class="table" width="100%">
    <tr>
      <th>Author</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>

    <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <td><%= link_to 'Show', article_path(article) %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article_path(article),
                          method: :delete,
                          data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<div align="center"><h1>New article</h1>

<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div align="center">
  <table class="table">
    <tr>
      <td><strong>Author:</strong>
        <%= @article.title %>
      </td>
    </tr>

    <tr>
      <td><strong>Text:</strong>
        <%= @article.text %></td>
    </tr>

    <!--Form to add article-->

  </table>

  <h2>Comments</h2>

  <table class="table" width="100%">
    <tr>
      <th><strong>Author:</strong></th>
      <th><strong>Comment:</strong></th>
    </tr>
    <% @article.comments.each do |comment| %>

        <tr>
          <td><%= comment.commenter %></td>

          <td><%= comment.body %></td>
          <td><%= link_to 'Show', comment_path(comment) %>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy Comment', [comment.article, comment],
                          method: :delete,
                          data: {confirm: 'Are you sure?'} %></td>


        </tr>
    <% end %>
  </table>


  <!--Form to display comment-->


  <h2>Add a comment:</h2>
  <%= form_for([@article, @article.comments.build]) do |f| %>

      <p>
        <%= f.text_area :body, size: "58x6" %>
      </p>
      <p>
        <%= f.submit %>
      </p>
  <% end %>

  <!--Form to add a comment-->


  <div class="c"><%= link_to 'Edit', edit_article_path(@article) %></div>

</div>

app/views/comments/edit.html.erb
<div align="center">
  <%= form_for @comment do |f| %>


      <h1> Edit comment</h1>
      <br>
      <%= f.text_area :body, size: "58x6" %>


      <p>
        <%= f.submit %>
      </p>

  <% end %>
</div>

app/views/comments/show.html.erb
<div align="center"><h2>Comment</h2>
  <table class="table">
    <tr>
      <td>
        <strong>Commenter:</strong>
        <%= @comment.commenter %>
      </td>
      <td><strong>Comment:</strong>
        <%= @comment.body %></td>
    </tr>
  </table>


  <h2>Comms</h2>
  <table class="table" width="100%">
    <tr>
      <th>Author</th>
      <th>Comm</th>
      <th colspan="3"></th>
    </tr>
    <% @comment.comms.each do |comm| %>

        <tr>
          <td><%= comm.commenter %></td>
          <td><%= comm.body %></td>
          <td><%= link_to 'Edit', edit_comm_path(comm) %></td>
          <td><%= link_to 'Destroy', [comm.comment, comm],
                          method: :delete,
                          data: {confirm: 'Are you sure?'} %></td>

        </tr>

    <% end %>
  </table>


  <h2>Add a comm:</h2>
  <%= form_for([@comment, @comment.comms.build]) do |f| %>

      <p>
        <%= f.text_area :body, size: "58x6" %>
      </p>
      <p>
        <%= f.submit %>
      </p>
  <% end %>

</div>

app/views/comms/edit.html.erb
<div align="center"> <%= form_for @comm do |f| %>


      <p>
        <h1>Change a comment</h1> <br>
        <%= f.text_area :body, size: "58x6" %>
      </p>

      <p>
        <%= f.submit %>
      </p>

  <% end %>
</div>

app/views/comms/show.html.erb
<div align="center"><h2>Comm</h2>
  <table class="table">
    <tr>
      <td>
        <strong>Commenter:</strong>
        <%= @comm.commenter %>
      </td>
      <td><strong>Comment:</strong>
        <%= @comm.body %></td>
    </tr>
  </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>forApplikey</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div align="center">
  <% flash.each do |key, message| %>
      <p class="<%= key %>"><%= message %></p>
  <% end %>
</div>
<div align="right">
  <% if user_signed_in? %>
      <span>Hi, <%= current_user.email %></span>
      <p class="c"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %><p>
  <% else %>
      <div class="c"><%= link_to 'Log in', new_user_session_path %> </div>
      <strong>OR</strong>
      <div class="c"> <%= link_to 'Sign up', new_user_registration_path %></div>
  <% end %>
  <p></p>
  <div class="c"><%= link_to 'Home', articles_path %></div>
</div>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>forApplikey</h1>
<%= link_to 'База клиентов', controller: 'articles' %>